### ISSUE TITLE
Fix getFocusPosition error

### ISSUE THREAD

**Issue by tellfa** [Khang-NT/KRecyclerView#6]
Hi, thanks for this librar. i want use this librar, but when use this and running application show me this error : 

`FATAL EXCEPTION: main
                  Process: com.tellfa.colony, PID: 23953
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int com.tellfa.colony.Components.BigRecyclerView.KRecyclerView.getFocusPosition()' on a null object reference
                      at com.tellfa.colony.Components.BigRecyclerView.KRecyclerView$EndlessAdapter.onBindViewHolder(KRecyclerView.java:217)
                      at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5822)
                      at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5855)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5091)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4967)
                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                      at android.view.View.layout(View.java:15654)
                      at android.view.ViewGroup.layout(ViewGroup.java:4969)
                      at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                      at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1364)
                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:852)
                      at android.view.View.layout(View.java:15654)
                      at android.view.ViewGroup.layout(ViewGroup.java:4969)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                      at android.view.View.layout(View.java:15654)
                      at android.view.ViewGroup.layout(ViewGroup.java:4969)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
                      at android.view.View.layout(View.java:15654)
                      at android.view.ViewGroup.layout(ViewGroup.java:4969)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                      at android.view.View.layout(View.java:15654)
                      at android.view.ViewGroup.layout(ViewGroup.java:4969)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
                      at android.view.View.layout(View.java:15654)
                      at android.view.ViewGroup.layout(ViewGroup.java:4969)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                      at android.view.View.layout(View.java:15654)
                      at android.view.ViewGroup.layout(ViewGroup.java:4969)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2102)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1859)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5875)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                      at android.view.Choreographer.doFrame(Choreographer.java:550)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5349)`

My Adapter codes:
`public class ProfileAdapter2 extends KRecyclerView.EndlessAdapter<ProfileAdapter2.profileViewHolder> {

    private List<R_AuthorModel> mDateSet;
    private Context mContext;

    public ProfileAdapter2(Context context, KRecyclerView kRecyclerView, List<R_AuthorModel> dataSet) {
        super(kRecyclerView);
        this.mContext = context;
        this.mDateSet = dataSet;
    }

    @Override
    public int getItemViewType_(int position) {
        return 0;
    }

    @Override
    public int getItemCount_() {
        return mDateSet.size();
    }

    @Override
    public void onBindViewHolder_(final profileViewHolder holder, int position) {
        holder.profile_post_title.setText(Html.fromHtml(mDateSet.get(position).getTitle()));

        if (mDateSet.get(position).getThumbnail_images().getMedium().getUrl() != null) {
            Glide.with(mContext)
                    .load(mDateSet.get(position).getThumbnail_images().getMedium().getUrl())
                    .placeholder(R.drawable.post_image)
                    .bitmapTransform(new CropCircleTransformation(mContext))
                    .centerCrop()
                    .override(50, 50)
                    .animate(android.R.anim.fade_in)
                    .into(holder.profile_post_image);
        }

        holder.profile_post_content.setText(Html.fromHtml(mDateSet.get(position).getContent()));

        holder.profile_dateTime.setText(Html.fromHtml(mDateSet.get(position).getDate()));

        holder.profile_post_image.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                int pos = holder.getPosition();
                R_AuthorModel model = mDateSet.get(pos);
                v.getContext().startActivity(new Intent(v.getContext(), PostShow_page.class)
                        .putExtra("title", model.getTitle())
                        .putExtra("image", model.getThumbnail())
                        .putExtra("content", model.getContent())
                        .putExtra("dateTime", model.getDate())
                        .putExtra("author", model.getCatAuthor().getName())
                        .putExtra("category", model.getCategories().get(0).getCatTitle()));

            }
        });
    }

    @Override
    public void onScaled(profileViewHolder holder, int position, float f) {
        holder.onScaled(f);
    }

    public void add(List<R_AuthorModel> models) {
        mDateSet.addAll(models);
        notifyDataSetChanged();
    }

    @Override
    public profileViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(mContext).inflate(R.layout.profile_content, parent, false);
        return new ProfileAdapter2.profileViewHolder(view);
    }

    public static class profileViewHolder extends RecyclerView.ViewHolder {

        private TextView profile_post_title, profile_post_content, profile_dateTime;
        private ImageView profile_post_image;

        float lastScale = 0;

        public profileViewHolder(View itemView) {
            super(itemView);

            profile_post_title = (TextView) itemView.findViewById(R.id.profile_content_title_text);
            profile_post_image = (ImageView) itemView.findViewById(R.id.profile_content_image_postImage);
            profile_post_content = (TextView) itemView.findViewById(R.id.profile_content_content_text);
            profile_dateTime = (TextView) itemView.findViewById(R.id.profile_content_date_text);
        }

        void onScaled(float f) {
            if (Math.abs(f - lastScale) > 0.05f) {
                lastScale = f;
                profile_post_content.setScaleX(f + 1);
                profile_post_content.setScaleY(f + 1);
            }
        }
    }
}
`

How can i fix this? Thanks

**Comment by Khang-NT** [comment]
Because of `kRecyclerView` in `ProfileAdapter2` constructor is `null`.

```java
public ProfileAdapter2(Context context, KRecyclerView kRecyclerView, List<R_AuthorModel> dataSet) {
        super(kRecyclerView);    // null pointer here, may be you findViewBy(wrong id)
        this.mContext = context;
        this.mDateSet = dataSet;
}
```

**Comment by tellfa** [comment]
this issue is ok, but i don't want use EndLess! how can i use  `extends  KRecyclerView.Adapter `instance of `extends KRecyclerView.EndlessAdapter `?
